/*
 * This file is part of AetasRaider.
 *
 *     AetasRaider is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     AetasRaider is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with AetasRaider.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.aetas.test;

import junit.framework.Assert;
import org.aetas.feedprocessors.CharacterActivityFeedParser;
import org.aetas.feedprocessors.GuildInfoFeedParser;
import org.aetas.model.WowCharacter;
import org.aetas.model.activity.CharacterActivity;
import org.aetas.model.activity.UnknownCharacterActivity;
import org.jdom.JDOMException;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.xml.sax.SAXException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * User: carlabramsson
 * Date: 2010-jan-29
 * Time: 22:11:24
 * To change this template use File | Settings | File Templates.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"/integration-test-context.xml"})
public class IntegrationTestGuildActivity {

    @Autowired
    CharacterActivityFeedParser characterActivityFeedParser;

    @Autowired
    GuildInfoFeedParser p;


    @Test
    public void test_parse_guild_feed() throws IOException, SAXException, JDOMException {

        List<UnknownCharacterActivity> unknownCharacterActivities = new ArrayList<UnknownCharacterActivity>();

        List<WowCharacter> characterList = p.getGuildMembers();
        for (WowCharacter wChar : characterList) {
            System.out.println(wChar);

            List<CharacterActivity> activity = characterActivityFeedParser.getCharacterActivityFromFeed(wChar, new Date());

            for (CharacterActivity entry : activity) {

                if (entry instanceof UnknownCharacterActivity) {
                    System.err.println(entry);
                    unknownCharacterActivities.add((UnknownCharacterActivity) entry);
                } else {
                    System.out.println(entry);
                }

            }

        }

        for (CharacterActivity entry : unknownCharacterActivities) {
            System.err.println(entry);
        }
        if (unknownCharacterActivities.size() > 0)
            Assert.fail("There are unknown activities: " + unknownCharacterActivities.size());


    }

    /*
UnknownCharacterActivity{id='null', date=Sat Nov 29 15:11:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [Collector's Edition: Frost Wyrm Whelp].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_pet_frostwyrm.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Collector\&#39;s Edition: Frost Wyrm Whelp (0)&#60;/strong\&#62;&#60;br /\&#62;Owner of the Wrath of the Lich King\&#39;s Collector\&#39;s Edition Frost Wyrm Whelp pet.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Theodora&#38;alink=81:9:683#ach683">Collector&#39;s Edition: Frost Wyrm Whelp</a>].'}
UnknownCharacterActivity{id='null', date=Sat Nov 29 15:10:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [WoW's 4th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 4th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 4th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Theodora&#38;alink=81:9:2398#ach2398">WoW&#39;s 4th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Fri Jan 15 21:44:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 1 times.', content='1 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Sat Jan 23 15:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 1 times.', content='1 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 20 22:05:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 4 times.', content='4 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Wed Dec 16 21:16:00 CET 2009, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 4 times.', content='4 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 02:10:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Vuwen&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 17:12:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Mela&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 23 14:18:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [WoW's 4th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 4th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 4th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Mela&#38;alink=81:9:2398#ach2398">WoW&#39;s 4th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Thu Nov 20 21:38:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [Sergeant].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_pvp_h_03.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Sergeant (0)&#60;/strong\&#62;&#60;br /\&#62;Earned the title, \&#34;Sergeant\&#34;.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Mela&#38;alink=81:9:453#ach453">Sergeant</a>].'}
UnknownCharacterActivity{id='null', date=Sat Sep 05 23:57:00 CEST 2009, wowCharacterId='null', title='Earned the feat of strength [Onyxia's Lair (Level 60)].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_boss_onyxia.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Onyxia\&#39;s Lair (Level 60) (0)&#60;/strong\&#62;&#60;br /\&#62;Defeat the classic, level 60 version of Onyxia.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Slinger&#38;alink=81:9:684#ach684">Onyxia&#39;s Lair (Level 60)</a>].'}
UnknownCharacterActivity{id='null', date=Tue Nov 24 22:13:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Sturk&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Tue Oct 21 19:58:00 CEST 2008, wowCharacterId='null', title='Earned the feat of strength [Onyxia's Lair (Level 60)].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_boss_onyxia.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Onyxia\&#39;s Lair (Level 60) (0)&#60;/strong\&#62;&#60;br /\&#62;Defeat the classic, level 60 version of Onyxia.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Eron&#38;alink=81:9:684#ach684">Onyxia&#39;s Lair (Level 60)</a>].'}
UnknownCharacterActivity{id='null', date=Wed Oct 15 20:38:00 CEST 2008, wowCharacterId='null', title='Earned the feat of strength [Sergeant].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_pvp_h_03.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Sergeant (0)&#60;/strong\&#62;&#60;br /\&#62;Earned the title, \&#34;Sergeant\&#34;.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Eron&#38;alink=81:9:453#ach453">Sergeant</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Nov 28 16:57:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Donrer&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Sep 05 23:57:00 CEST 2009, wowCharacterId='null', title='Earned the feat of strength [Onyxia's Lair (Level 60)].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_boss_onyxia.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Onyxia\&#39;s Lair (Level 60) (0)&#60;/strong\&#62;&#60;br /\&#62;Defeat the classic, level 60 version of Onyxia.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Donrer&#38;alink=81:9:684#ach684">Onyxia&#39;s Lair (Level 60)</a>].'}
UnknownCharacterActivity{id='null', date=Fri Jan 22 00:48:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 6 times.', content='6 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 13:34:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Isabelf&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Nov 18 21:10:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (25 player)] 5 times.', content='5 Times completed the Trial of the Crusader (25 player).'}
UnknownCharacterActivity{id='null', date=Wed Nov 18 21:10:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Grand Crusader (10 player)] 5 times.', content='5 Times completed the Trial of the Grand Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Thu Oct 29 21:03:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 4 times.', content='4 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sat Jan 23 15:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 6 times.', content='6 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Fri Jan 29 15:43:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 9 times.', content='9 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Thu Jan 14 10:40:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 1 times.', content='1 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Tue Nov 24 10:02:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Trisk&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Thu Dec 03 20:40:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 6 times.', content='6 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Dec 02 20:30:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Grand Crusader (10 player)] 7 times.', content='7 Times completed the Trial of the Grand Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Dec 02 20:30:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (25 player)] 7 times.', content='7 Times completed the Trial of the Crusader (25 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 18:07:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Beethoofen&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 11:27:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Bidash&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Tue Oct 13 21:01:00 CEST 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 1 times.', content='1 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Fri Jan 22 00:48:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 3 times.', content='3 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 21:51:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Paladinia&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 23 13:56:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [WoW's 4th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 4th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 4th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Paladinia&#38;alink=81:9:2398#ach2398">WoW&#39;s 4th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 16:51:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Coster&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 20:05:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Hellron&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 3 times.', content='3 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 07:04:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Zoddom&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 1 times.', content='1 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Fri Jan 22 00:48:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 2 times.', content='2 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Tue Dec 08 23:45:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 2 times.', content='2 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 23:55:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Vaal&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Fri Jan 22 00:48:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 4 times.', content='4 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 11:56:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Eriman&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Tue Dec 15 01:21:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 2 times.', content='2 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 20 21:43:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 1 times.', content='1 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Fri Jan 29 21:14:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (25 player)] 5 times.', content='5 Times completed the Trial of the Crusader (25 player).'}
UnknownCharacterActivity{id='null', date=Fri Jan 29 21:14:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Grand Crusader (10 player)] 5 times.', content='5 Times completed the Trial of the Grand Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 11 times.', content='11 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Thu Oct 08 21:07:00 CEST 2009, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 1 times.', content='1 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Wed Nov 25 14:18:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Ewani&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sat Jan 23 15:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 1 times.', content='1 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Thu Dec 03 13:24:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 4 times.', content='4 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 10:47:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Dimmalimm&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 11:06:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Myto&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Fri Dec 25 05:34:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [Grand Black War Mammoth].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/ability_mount_mammoth_black.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Grand Black War Mammoth (0)&#60;/strong\&#62;&#60;br /\&#62;Obtain a Grand Black War Mammoth.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Riond&#38;alink=81:9:2081#ach2081">Grand Black War Mammoth</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 19:34:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Riond&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Tue Nov 24 22:40:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Morco&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 5 times.', content='5 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Fri Jan 22 00:48:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 5 times.', content='5 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 10 times.', content='10 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 22:34:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Snodden&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Sep 20 20:54:00 CEST 2009, wowCharacterId='null', title='Earned the feat of strength [Timear Foresees].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/spell_arcane_focusedpower.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Timear Foresees (0)&#60;/strong\&#62;&#60;br /\&#62;Complete the Northrend daily dungeon quests listed below.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Snodden&#38;alink=81:9:2018#ach2018">Timear Foresees</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 20:16:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Phant&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Jan 20 21:43:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 5 times.', content='5 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Tue Dec 15 01:21:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 3 times.', content='3 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Nov 25 21:15:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (25 player)] 2 times.', content='2 Times completed the Trial of the Crusader (25 player).'}
UnknownCharacterActivity{id='null', date=Wed Nov 25 21:15:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Grand Crusader (10 player)] 2 times.', content='2 Times completed the Trial of the Grand Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Fri Dec 04 14:24:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Oss&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 20:13:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Dermordien&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 19:45:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Eremeli&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Dec 16 21:16:00 CET 2009, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 1 times.', content='1 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Mon Nov 23 22:19:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Luma&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Dec 12 16:31:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [Grand Black War Mammoth].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/ability_mount_mammoth_black.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Grand Black War Mammoth (0)&#60;/strong\&#62;&#60;br /\&#62;Obtain a Grand Black War Mammoth.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Uggluk&#38;alink=81:9:2081#ach2081">Grand Black War Mammoth</a>].'}
UnknownCharacterActivity{id='null', date=Tue Dec 08 23:45:00 CET 2009, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 5 times.', content='5 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 20 16:12:00 CET 2010, wowCharacterId='null', title='Has now completed [Mr. Bigglesworth kills] 4 times.', content='4 Mr. Bigglesworth kills.'}
UnknownCharacterActivity{id='null', date=Tue Nov 24 02:25:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Zindor&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Thu Nov 26 03:25:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Ahab&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 2 times.', content='2 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Wed Jan 27 17:34:00 CET 2010, wowCharacterId='null', title='Has now completed [Times completed the Trial of the Crusader (10 player)] 3 times.', content='3 Times completed the Trial of the Crusader (10 player).'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 13:38:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Aleanathem&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Mon Aug 03 19:22:00 CEST 2009, wowCharacterId='null', title='Earned the feat of strength [Collector's Edition: Frost Wyrm Whelp].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_pet_frostwyrm.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Collector\&#39;s Edition: Frost Wyrm Whelp (0)&#60;/strong\&#62;&#60;br /\&#62;Owner of the Wrath of the Lich King\&#39;s Collector\&#39;s Edition Frost Wyrm Whelp pet.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Aleanathem&#38;alink=81:9:683#ach683">Collector&#39;s Edition: Frost Wyrm Whelp</a>].'}
UnknownCharacterActivity{id='null', date=Tue May 19 07:37:00 CEST 2009, wowCharacterId='null', title='Earned the feat of strength [Vampire Hunter].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/ability_hunter_pet_bat.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Vampire Hunter (0)&#60;/strong\&#62;&#60;br /\&#62;Slew Prince Tenris Mirkblood and acquired his Vampiric Batling pet.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Evl&#38;alink=81:9:2456#ach2456">Vampire Hunter</a>].'}
UnknownCharacterActivity{id='null', date=Mon Nov 24 06:59:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [WoW's 4th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 4th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 4th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Evl&#38;alink=81:9:2398#ach2398">WoW&#39;s 4th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 02 01:31:00 CET 2008, wowCharacterId='null', title='Earned the feat of strength [Champion].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/achievement_pvp_h_10.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;Champion (0)&#60;/strong\&#62;&#60;br /\&#62;Earned the title, \&#34;Champion\&#34;.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Evl&#38;alink=81:9:447#ach447">Champion</a>].'}
UnknownCharacterActivity{id='null', date=Sun Nov 29 22:17:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Fjant&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}
UnknownCharacterActivity{id='null', date=Sat Jan 30 01:00:00 CET 2010, wowCharacterId='null', title='There are no entries that match the filter parameters.', content='null'}
UnknownCharacterActivity{id='null', date=Sun Nov 22 20:57:00 CET 2009, wowCharacterId='null', title='Earned the feat of strength [WoW's 5th Anniversary].', content='Earned the feat of strength [<a onmouseover="setTipText('&#60;div class=\&#34;myTable\&#34; style=\&#34;\&#34;\&#62;&#60;img src=\&#34;/wow-icons/_images/51x51/inv_misc_celebrationcake_01.jpg\&#34; class=\&#34;ach_tooltip\&#34; /\&#62;&#60;strong style=\&#34;color: #fff;\&#34;\&#62;WoW\&#39;s 5th Anniversary (0)&#60;/strong\&#62;&#60;br /\&#62;Logged in during WoW\&#39;s 5th Anniversary.&#60;/div\&#62;')" class="achievement staticTip" href="http://eu.wowarmory.com//character-achievements.xml?r=The+Venture+Co&#38;cn=Hippolyte&#38;alink=81:9:4400#ach4400">WoW&#39;s 5th Anniversary</a>].'}

     */
}
